baseURL = 'https://cristianoreiss.github.io/'
languageCode = 'pt-br'
title = 'Cristiano Reis'
theme = 'PaperMod'

[params]
    defaultTheme = "dark"
    [markup.goldmark.renderer]
        unsafe = true
    
    showRecentPostsOnHomePage = true 
    pagesize = 5

[params.profileMode]
    enabled = true
    title = "Cristiano Reis"
    subtitle = "Estagiário de Solução de Dados @ Radix | Estudante de Sistemas de Informação @ UNIRIO"
    displayFullLangName = true
    imageUrl = "/images/perfil_crop.jpeg"
    imageTitle = "Cristiano Reis"
    imageWidth = 160
    imageHeight = 160
    buttons = [
        { name = "Projetos", url = "/projects"},
        { name = "Certificações", url = "/certifications"},
        { name = "Sobre", url = "/about" },
        { name = "Currículo", url = "/pdf/Cristiano-Reis-Curriculo.pdf"}
    ]

[[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/cristianorreis/"

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/cristianoreiss"

[[params.socialIcons]]
    name = "email"
    url = "mailto:cristianoreis0515@gmail.com"

[[menu.main]]
    identifier = "projects"
    name = "Projetos"
    url = "/projects"
    weight = 10

[[menu.main]]
    identifier = "certifications"
    name = "Certificações"
    url = "/certifications"
    weight = 20

[[menu.main]]
    identifier = "about"
    name = "Sobre"
    url = "/about"
    weight = 30